name: Build my Solution
on: push

jobs:
  build:
    name: Build the Solution
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repo
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List files
        run: ls
      - name: See if dotnet exists?
        run: dotnet
      - name: See if npm exists?
        run: npm
